#! /bin/sh
#==================================================================================
#  _______    ________  _______   __   __  ___  ___      ___   _______    ______   
# |   _  "\  /"       )|   __ "\ |"  |/  \|  "||"  \    /"  | /"      \  /" _  "\  
# (. |_)  :)(:   \___/ (. |__) :)|'  /    \:  | \   \  //   ||:        |(: ( \___) 
# |:     \/  \___  \   |:  ____/ |: /'        | /\\  \/.    ||_____/   ) \/ \      
# (|  _  \\   __/  \\  (|  /      \//  /\'    ||: \.        | //      /  //  \ _   
# |: |_)  :) /" \   :)/|__/ \     /   /  \\   ||.  \    /:  ||:  __   \ (:   _) \  
# (_______/ (_______/(_______)   |___/    \___||___|\__/|___||__|  \___) \_______) 
#                                                                                  
#==================================================================================

#==============================
#===== Auto start
#==============================
# HiDPI; 1.5scale;
xrandr --dpi 144

# GDK app scale
export GDK_DPI_SCALE=1.5

# QT app theme and scale VARIANT (works well on dolphin and clementine)(optional | QT APP DEMAND)
export $(grep -v '^#' $HOME/.config/.decorate_qt_app | xargs -d '\n')

# Start compositer
nohup picom -f >/dev/null 2>&1 &  # effct of fade

# Set background image randonly with pywal
wal  -ste -lq -i $HOME/Pictures/Home_Slide

# Blur desktop wallpaper when windows are open
sh $HOME/Scripts/wallblur.sh &>/dev/null &

# Polybar; to make sure services already boot
sh -c "sleep 3s $HOME/.config/polybar/launch.sh"

# Message notifier
/usr/bin/dunst &

# Cache lock images for betterlockscrren
/usr/bin/betterlockscreen -u ~/Pictures/ScreenLock/ &

# Input method fcitx5 (optional | IM DEMAND)
nohup fcitx5 >/dev/null 2>&1 &

# core
pgrep -x sxhkd > /dev/null || sxhkd &




#========================================
#===== Bspwm config
#========================================
# Virtual desktop setting; Also multi monitor supplied
bspc monitor -d I II III IV V VI VII

# Coloring
bspc config active_border_color	 "#81a1c1"
bspc config normal_border_color	 "#4c566a"
bspc config focused_border_color "#b48ead"

bspc config border_width         2
bspc config window_gap           10

# Padding config (Seems)
#brpc config top_padding 36
#bspc config left_padding 0
#bspc config right_padding 0
#bspc config bottom_padding 36

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true




#========================================
#===== Bspwm rule
#========================================

# Workspace 1 (Home)
bspc rule -a TelegramDesktop desktop='^1'
bspc rule -a 微信    desktop='^1'             follow=on focus=on
bspc rule -a qq   desktop='^1'                follow=on focus=on
bspc rule -a picgo   desktop='^1'             follow=on focus=on

# Workspace 2 (Web browser)
bspc rule -a firefox desktop='^2'             follow=on focus=on locked=on
bspc rule -a Notion detktop='^2'              follow=on focus=on

# Workspace 3 (Code editor)
bspc rule -a St:st:nvim desktop='^3'          follow=on focus=on locked=on
bspc rule -a St:st:ranger desktop='^3'        follow=on focus=on locked=on

# Workspace 4 (Reading and Text-editors)
bspc rule -a Typora desktop='^4'              follow=on focus=on locked=on
bspc rule -a Zathura desktop='^4' state=tiled follow=on focus=on

# Workspace 5 (Sysinfo, MC and anythingelse)
bspc rule -a St:st:btm desktop='^5'           follow=on focus=on
bspc rule -a MultiMC5 desktop='^5'            follow=on focus=on

# Workspace 6 (Music and Video)
bspc rule -a Clementine desktop='^6'          follow=on focus=on 
bspc rule -a netease-cloud-music desktop='^6' follow=on focus=on
bspc rule -a vlc desktop='^6'                 follow=on focus=on

# Others
bspc rule -a Screenkey manage=off
