#! /bin/sh
#==================================================================================
#  _______    ________  _______   __   __  ___  ___      ___   _______    ______   
# |   _  "\  /"       )|   __ "\ |"  |/  \|  "||"  \    /"  | /"      \  /" _  "\  
# (. |_)  :)(:   \___/ (. |__) :)|'  /    \:  | \   \  //   ||:        |(: ( \___) 
# |:     \/  \___  \   |:  ____/ |: /'        | /\\  \/.    ||_____/   ) \/ \      
# (|  _  \\   __/  \\  (|  /      \//  /\'    ||: \.        | //      /  //  \ _   
# |: |_)  :) /" \   :)/|__/ \     /   /  \\   ||.  \    /:  ||:  __   \ (:   _) \  
# (_______/ (_______/(_______)   |___/    \___||___|\__/|___||__|  \___) \_______) 
#                                                                                  
#==================================================================================

#==============================
#===== Monitor setup: DPI setting for multi monitors:
#==============================
# Primary: HiDPI:144DPI;
export MAIN_DPI=144
export PRIMARY_MONITOR=$(xrandr -q | grep primary | awk '{print $1}')
xrandr --output $PRIMARY_MONITOR --dpi $MAIN_DPI --scale 1x1

# GDK app scale
export GDK_DPI_SCALE=1.5

# QT app theme and scale VARIANT (works well on dolphin and clementine)(optional | QT APP DEMAND)
export $(grep -v '^#' $HOME/.config/.decorate_qt_app | xargs -d '\n')

# Virtual desktop setting; Also multi monitor supplied
bspc monitor $PRIMARY_MONITOR -d I II III IV V VI VII


# Sencondary: normal DPI, check it statically;
OTHER_MONITORS=$(xrandr -q | grep ' connected' | awk '{print $1}' | grep -v ${PRIMARY_MONITOR} | wc -l)
if [[ $OTHER_MONITORS == 1 ]]; then
	export SECONDARY_MONITOR=$(xrandr -q | grep ' connected' | awk '{print $1}' | grep -v ${PRIMARY_MONITOR})
	xrandr --output $SECONDARY_MONITOR  --mode 1920x1080 --scale 1.5x1.5 --fb 5760x1800 --pos 0x0
	xrandr --output $PRIMARY_MONITOR --scale 1x1 --pos 2880x0
	bspc monitor $SECONDARY_MONITOR -d VIII IX X
	# Bspwm automatically make the order from left to right, form top to down.
	# In my case, primary monitor lay at the right, so the order will be I II III for $SECONDARY, while IV ... X for $PRIMARY
	# To change that, execute command below once.
	# TODO: currently, everytime after monitors suspend, the command below must be executed once more.
	bspc monitor $PRIMARY_MONITOR -s $SECONDARY_MONITOR
fi

#==============================
#===== Auto start
#==============================
# Start compositer
nohup picom -f >/dev/null 2>&1 &  # effct of fade

# Set background image randonly with pywal
wal  -ste -lq -i $HOME/Pictures/Home_Slide

# Blur desktop wallpaper when windows are open
sh $HOME/Scripts/wallblur.sh &>/dev/null &

# Polybar; to make sure services already boot
sh -c "sleep 3s; $HOME/.config/polybar/launch.sh"

# Message notifier
/usr/bin/dunst &

# Cache lock images for betterlockscrren
/usr/bin/betterlockscreen -u ~/Pictures/ScreenLock/ &

# Input method fcitx5 (optional | IM DEMAND)
nohup fcitx5 >/dev/null 2>&1 &

# core
pgrep -x sxhkd > /dev/null || sxhkd &




#========================================
#===== Bspwm config
#========================================
# Coloring
bspc config active_border_color	 "#81a1c1"
bspc config normal_border_color	 "#4c566a"
bspc config focused_border_color "#b48ead"

bspc config border_width         2
bspc config window_gap           10

# Padding config (Seems)
#brpc config top_padding 36
#bspc config left_padding 0
#bspc config right_padding 0
#bspc config bottom_padding 36

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true




#========================================
#===== Bspwm rule
#========================================

# Workspace 1 (Home)
bspc rule -a TelegramDesktop desktop='^1'
bspc rule -a 微信    desktop='^1'             follow=on focus=on
bspc rule -a qq   desktop='^1'                follow=on focus=on
bspc rule -a picgo   desktop='^1'             follow=on focus=on

# Workspace 2 (Web browser)
bspc rule -a firefox desktop='^2'             follow=on focus=on locked=on
bspc rule -a Notion detktop='^2'              follow=on focus=on

# Workspace 3 (Code editor)
bspc rule -a St:st:nvim desktop='^3'          follow=on focus=on locked=on

# Workspace 4 (Reading and Text-editors)
bspc rule -a Typora desktop='^4'              follow=on focus=on locked=on
bspc rule -a Zathura desktop='^4' state=tiled follow=on focus=on

# Workspace 5 (Sysinfo, MC and anythingelse)
bspc rule -a St:st:btm desktop='^5'           follow=on focus=on
bspc rule -a MultiMC5 desktop='^5'            follow=on focus=on

# Workspace 6 (Music and Video)
bspc rule -a Clementine desktop='^6'          follow=on focus=on 
bspc rule -a netease-cloud-music desktop='^6' follow=on focus=on
bspc rule -a vlc desktop='^6'                 follow=on focus=on

# Others
bspc rule -a Screenkey manage=off
